language: ruby
script:
  - git config user.name 'test'
  - git config user.email 'example@example.com'
  - bundle exec rake
rvm:
  - 2.2
  - 2.1
  - 2.0
notifications:
  - on_success: never
  - on_failure: always
